# Generated by Django 4.2.6 on 2023-10-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_osoba_options_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta'), (3, 'Inna')], max_length=1),
        ),
    ]
