# Generated by Django 4.2.6 on 2023-11-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('data_urodzenia', models.DateField()),
                ('adres', models.TextField()),
                ('numer_telefonu', models.CharField(max_length=15)),
                ('adres_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PersonelMedyczny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('specjalizacja', models.CharField(max_length=100)),
                ('numer_identyfikacyjny', models.CharField(max_length=10, unique=True)),
                ('adres', models.TextField()),
                ('numer_telefonu', models.CharField(max_length=15)),
                ('adres_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RejestracjaWizyt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wizyty', models.DateField()),
                ('godzina_wizyty', models.TimeField()),
                ('opis_wizyty', models.TextField()),
                ('status_wizyty', models.CharField(choices=[('p', 'Planowana'), ('o', 'Odwołana'), ('z', 'Zakończona')], default='p', max_length=20)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szpital.personelmedyczny')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szpital.pacjent')),
            ],
        ),
        migrations.CreateModel(
            name='OddzialSzpitalny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_oddzialu', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField()),
                ('personel', models.ManyToManyField(to='szpital.personelmedyczny')),
            ],
        ),
    ]
